Repository Park-sETF/front, pull requests merged in 2024-12, with the labels that each got.

#84 create MyReport
  package-lock.json
  package.json
  src/components/home/MyReport.jsx
  src/components/home/Tab.jsx
  src/routes/login/page.jsx
  src/routes/membership/page.jsx
Labels: :sparkles: Feature

#90 create MyReport
  src/components/home/MyReport.jsx
  src/components/home/Tab.jsx
Labels: :sparkles: Feature

#91 edit MyReport
  src/components/home/MyReport.jsx
Labels: :bug: Debug

#102 Refactor/#85 chart
  src/components/myPocket/Chart.jsx
Labels: :recycle: Refactoring

#103 Refactor/#85 chart
  src/components/etfDetail/ETFDetail.jsx
  src/components/etfDetail/MyETFDetail.jsx
  src/components/home/List.jsx
  src/components/myPocket/Chart.jsx
Labels: :recycle: Refactoring

#107 Refactor/#85 chart
  src/components/etfDetail/ETFDetail.jsx
  src/components/etfDetail/MyETFDetail.jsx
  src/components/home/ETFButtonList.jsx
  src/components/home/List.jsx
  src/components/home/RankingUserInfo.jsx
  src/components/home/Tab.jsx
  src/components/home/UserInfo.jsx
  src/components/ranking/RankingUserInfo.jsx
  src/components/stock/Chart.jsx
  src/index.css
Labels: :recycle: Refactoring

#113 Feat/#112 feat pwa설정
  index.html
  public/about.txt
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/site.webmanifest
Labels: :sparkles: Feature

#117 Refactor/#116 ranking chart
  src/components/home/List.jsx
  src/components/myPocket/Chart.jsx
  src/components/ranking/RankingDetail.jsx
  src/components/ranking/RankingPage.jsx
  src/components/ranking/RankingUserInfo.jsx
  src/index.css
  src/routes/signup/page.jsx
  src/routes/user/CreateETF.jsx
Labels: :recycle: Refactoring

#121 Feat/#118 app install button
  package-lock.json
  package.json
  public/service-worker.js
  public/site.webmanifest
  src/components/etfDetail/ETFDetail.jsx
  src/components/home/UserInfo.jsx
  src/components/modal/CustomModal.css
  src/components/modal/CustomModal.jsx
  src/components/myPocket/Chart.jsx
  src/components/stock/Chart.jsx
  src/main.jsx
  src/routers/main-router.jsx
  src/routes/user/CreateETF.jsx
  src/serviceWorkerRegistration.js
  src/stores/auth/authSlice.js
Labels: :recycle: Refactoring

#128 Refactor/#127 UI
  src/components/etfDetail/ETFDetail.jsx
  src/components/etfDetail/MyETFDetail.jsx
  src/components/layouts/Layout.jsx
  src/components/myPocket/Chart.css
  src/components/myPocket/Chart.jsx
  src/components/myPocket/Detail.css
Labels: :recycle: Refactoring

#134 refactor: grade ui (#127)
  src/components/grade/GradeBenefits.jsx
  src/components/grade/MyGrade.jsx
  src/components/home/UserInfo.jsx
  src/components/ranking/RankingUserInfo.jsx
Labels: :recycle: Refactoring

#135 Refactor/#127 grade UI
  src/components/buttons/AppInstallButton.jsx
  src/components/home/UserInfo.jsx
  src/components/layouts/InstallPwa.jsx
  src/components/myPocket/Chart.jsx
  src/components/ranking/RankingUserInfo.jsx
  src/lib/apis/auth.js
  src/routes/init/page.jsx
  src/stores/auth/authSlice.js
Labels: :recycle: Refactoring

#136 fix: chart.jsx
  src/components/myPocket/Chart.jsx
Labels: :recycle: Refactoring

#137 fix: stock.jsx
  src/components/index.js
  src/components/myPocket/Chart.jsx
  src/components/stock/Chart.jsx
Labels: :recycle: Refactoring

#138 fix : stock images (#127)
  src/components/stock/Chart.jsx
Labels: :recycle: Refactoring
